<?php
function unit_page_start(string $title, string $active = 'home'): void {
    global $unit_config, $pdo;
    $settings = unit_settings($pdo);
    $theme = $unit_config['theme'];
    $profileActive = in_array($active, ['profile', 'programs'], true);
    ?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo unit_e($title . ' - ' . $settings['name']); ?></title><meta name="description" content="<?php echo unit_e($settings['description']); ?>"><link rel="stylesheet" href="<?php echo unit_asset('assets/css/style.css'); ?>"><link rel="stylesheet" href="<?php echo unit_asset('assets/css/foundation-refresh.css'); ?>"><style>:root{--primary:<?php echo unit_e($theme['primary']); ?>;--primary-dark:<?php echo unit_e($theme['primary_dark']); ?>;--accent:<?php echo unit_e($theme['accent']); ?>;--soft:<?php echo unit_e($theme['soft']); ?>;--ink:<?php echo unit_e($theme['ink']); ?>}</style></head><body>
<header class="site-header"><div class="shell nav-shell"><a class="brand" href="index.php"><span class="brand-mark-wrap"><img class="brand-mark" src="<?php echo unit_asset('assets/images/logo.png'); ?>" alt="Logo <?php echo unit_e($settings['name']); ?>"></span><span><strong><?php echo unit_e($settings['name']); ?></strong><small>SIT Permata Hati Bekasi</small></span></a><button class="menu-toggle" type="button" aria-label="Buka menu" aria-expanded="false" data-menu-toggle><span></span><span></span><span></span></button><nav class="main-nav" data-main-nav><a class="<?php echo $active==='home'?'active':''; ?>" href="index.php">Beranda</a><div class="nav-dropdown"><button type="button" class="nav-dropdown-trigger <?php echo $profileActive?'active':''; ?>" aria-expanded="false" data-nav-dropdown>Profil <svg viewBox="0 0 10 6" aria-hidden="true"><path d="m1 1 4 4 4-4"/></svg></button><div class="nav-dropdown-menu"><a class="<?php echo $active==='profile'?'active':''; ?>" href="profile.php">Profil Unit</a><a class="<?php echo $active==='programs'?'active':''; ?>" href="programs.php">Program</a></div></div><a class="<?php echo $active==='activities'?'active':''; ?>" href="activities.php">Kegiatan</a><a class="<?php echo $active==='gallery'?'active':''; ?>" href="gallery.php">Galeri</a><a class="<?php echo $active==='news'?'active':''; ?>" href="news.php">Berita</a><a class="<?php echo $active==='achievements'?'active':''; ?>" href="achievements.php">Prestasi</a><a class="<?php echo $active==='brochures'?'active':''; ?>" href="brochures.php">Brosur</a><a class="nav-cta <?php echo $active==='spmb'?'active':''; ?>" href="spmb.php">SPMB</a><a class="<?php echo $active==='contact'?'active':''; ?>" href="contact.php">Kontak</a></nav></div></header>
<main>
<?php }

function unit_page_end(): void { global $pdo; $settings=unit_settings($pdo); ?>
</main><footer class="site-footer"><div class="shell footer-grid"><section><a class="brand footer-brand" href="index.php"><img class="brand-mark" src="<?php echo unit_asset('assets/images/logo.png'); ?>" alt="Logo <?php echo unit_e($settings['name']); ?>"><span><strong><?php echo unit_e($settings['name']); ?></strong><small>SIT Permata Hati Bekasi</small></span></a><p><?php echo unit_e($settings['tagline']); ?></p><a class="back-foundation" href="../index.php">Kembali ke Website Yayasan</a></section><section><h2>Jelajahi</h2><a href="profile.php">Profil Unit</a><a href="programs.php">Program</a><a href="activities.php">Kegiatan</a><a href="gallery.php">Galeri</a></section><section><h2>Kontak</h2><p><?php echo nl2br(unit_e($settings['address'])); ?></p><a href="tel:<?php echo unit_e(preg_replace('/[^0-9+]/','',$settings['phone'])); ?>"><?php echo unit_e($settings['phone']); ?></a><a href="mailto:<?php echo unit_e($settings['email']); ?>"><?php echo unit_e($settings['email']); ?></a></section></div><div class="footer-bottom">&copy; <?php echo date('Y'); ?> <?php echo unit_e($settings['name']); ?>. Bagian dari SIT Permata Hati Bekasi.</div></footer><script src="<?php echo unit_asset('assets/js/app.js'); ?>"></script></body></html>
<?php }
