<?php
require_once __DIR__ . '/bootstrap.php';
$pdo = unit_db();
require_once __DIR__ . '/layout.php';
$page = $unit_page ?? 'home';
$settings = unit_settings($pdo);

if ($page === 'spmb' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $formMessage = ''; $formError = '';
    if (!unit_verify_csrf($_POST['csrf'] ?? '')) $formError = 'Sesi formulir tidak valid. Silakan muat ulang halaman.';
    else {
        $parent = trim($_POST['parent_name'] ?? ''); $child = trim($_POST['child_name'] ?? ''); $phone = trim($_POST['phone'] ?? '');
        if ($parent === '' || $child === '' || $phone === '') $formError = 'Nama orang tua, nama calon siswa, dan WhatsApp wajib diisi.';
        else { $stmt=$pdo->prepare('INSERT INTO unit_enrollments (unit_slug,parent_name,child_name,phone,email,message) VALUES (?,?,?,?,?,?)'); $stmt->execute([UNIT_SLUG,$parent,$child,$phone,trim($_POST['email']??''),trim($_POST['message']??'')]); $message='Assalamu\'alaikum, saya '.$parent.' ingin mendaftarkan '.$child.' ke '.$settings['name'].'.'; header('Location: https://wa.me/'.preg_replace('/\D/','',$settings['whatsapp']).'?text='.rawurlencode($message)); exit; }
    }
}

function unit_icon(string $name): string { $icons=['spark'=>'✦','heart'=>'♡','blocks'=>'▦','book'=>'▤','star'=>'★','flag'=>'⚑']; return $icons[$name]??'✦'; }
function unit_cards(array $rows, string $class, string $empty): void { if(!$rows){echo '<p class="empty-state">'.unit_e($empty).'</p>';return;} echo '<div class="card-grid '.$class.'">';foreach($rows as $row){$image=unit_media($row['image']??'');echo '<article class="content-card">'.($image?'<div class="card-image"><img src="'.unit_e($image).'" alt="'.unit_e($row['title']).'"></div>':'').'<div class="card-copy">'.(!empty($row['meta'])?'<span class="card-meta">'.unit_e($row['meta']).'</span>':'').'<h2>'.unit_e($row['title']).'</h2><p>'.unit_e($row['summary']??'').'</p></div></article>';}echo '</div>'; }
function unit_page_banner(string $eyebrow, string $title, string $text): void { echo '<section class="page-banner"><div class="shell"><span class="eyebrow">'.unit_e($eyebrow).'</span><h1>'.unit_e($title).'</h1><p>'.unit_e($text).'</p></div></section>'; }
function unit_home_notices(): array {
    $notices = [
        'daycare' => ['Pengasuhan hangat untuk usia dini', 'Stimulasi motorik, sensori, dan bahasa', 'Pembiasaan doa dan adab setiap hari', 'Konsultasi bersama pendidik Daycare Permata Hati'],
        'tkit' => ['Belajar sambil bermain untuk anak usia 4-6 tahun', 'Tahsin dan hafalan surat pendek', 'Kegiatan kreatif serta eksplorasi luar ruang', 'Pendaftaran TKIT Permata Hati Bekasi dibuka'],
        'sdit' => ['Akademik, Al-Quran, dan karakter dalam satu proses', 'Tahfidz sesuai target pembelajaran', 'Literasi, seni, olahraga, dan prestasi siswa', 'Informasi pendaftaran SDIT tersedia melalui admin'],
        'smpit' => ['Akademik kuat dan pembinaan remaja muslim', 'Tahfidz lanjutan serta mentoring siswa', 'Proyek sains, digital, olahraga, dan kepemimpinan', 'Informasi pendaftaran SMPIT tersedia melalui admin'],
    ];
    return $notices[UNIT_SLUG] ?? $notices['sdit'];
}

if ($page === 'home') {
    unit_page_start('Beranda', 'home'); $programs=unit_content($pdo,'program',3); $activities=unit_content($pdo,'activity',3); $achievements=unit_content($pdo,'achievement',3); $albums=unit_albums($pdo); $notices=unit_home_notices(); ?>
<section class="hero hero-foundation"><div class="hero-image" style="background-image:url('<?php echo unit_e(unit_media($unit_config['hero_image'])); ?>')"></div><div class="hero-shade"></div><div class="hero-motion-orbit orbit-one"></div><div class="hero-motion-orbit orbit-two"></div><div class="shell hero-content"><span class="eyebrow light">SIT PERMATA HATI BEKASI</span><h1><?php echo unit_e($settings['name']); ?></h1><p><?php echo unit_e($settings['description']); ?></p><div class="hero-actions"><a class="button button-accent" href="spmb.php">Daftar Sekarang</a><a class="button button-ghost" href="profile.php">Kenali Unit Kami</a></div><div class="hero-unit-note"><span><?php echo unit_e(strtoupper($unit_config['short_name'])); ?></span><p><?php echo unit_e($settings['tagline']); ?></p></div><div class="hero-facts"><span><b>Islamic</b><small>Learning culture</small></span><span><b>Bekasi</b><small>Tambun Selatan</small></span><span><b>SPMB</b><small>Informasi tersedia</small></span></div></div></section>
<section class="unit-notice-bar" aria-label="Informasi <?php echo unit_e($settings['name']); ?>"><div class="unit-notice-window"><div class="unit-notice-track"><?php foreach(array_merge($notices,$notices) as $notice): ?><span><i></i><?php echo unit_e($notice); ?></span><?php endforeach; ?></div></div></section>
<section class="section intro-section"><div class="shell intro-grid"><div><span class="eyebrow">TUMBUH BERSAMA</span><h2>Ruang belajar yang mendampingi setiap langkah anak.</h2></div><p><?php echo unit_e($settings['tagline']); ?> Kami membangun pengalaman belajar yang aman, aktif, dan bermakna bersama keluarga.</p></div></section>
<section class="section section-soft"><div class="shell"><div class="section-head"><span class="eyebrow">PROGRAM UNGGULAN</span><h2>Belajar sesuai tahap tumbuh kembang</h2></div><div class="feature-grid"><?php foreach($programs as $program): ?><article class="feature-card"><span class="feature-icon"><?php echo unit_icon('spark'); ?></span><h3><?php echo unit_e($program['title']); ?></h3><p><?php echo unit_e($program['summary']); ?></p></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="shell"><div class="section-head line-head"><div><span class="eyebrow">KEGIATAN</span><h2>Hari-hari penuh eksplorasi</h2></div><a class="text-link" href="activities.php">Lihat semua kegiatan</a></div><?php unit_cards($activities,'activity-grid','Kegiatan akan segera hadir.'); ?></div></section>
<section class="section section-primary"><div class="shell"><div class="section-head light-head"><div><span class="eyebrow light">POTRET SEKOLAH</span><h2>Setiap momen adalah proses bertumbuh</h2></div><a class="text-link light-link" href="gallery.php">Buka galeri</a></div><div class="album-strip"><?php foreach(array_slice($albums,0,3) as $album): ?><a href="gallery.php?album=<?php echo (int)$album['id']; ?>" class="album-tile" style="background-image:url('<?php echo unit_e(unit_media($album['cover_image'])); ?>')"><span><?php echo unit_e($album['title']); ?></span></a><?php endforeach; ?></div></div></section>
<section class="section"><div class="shell"><div class="section-head line-head"><div><span class="eyebrow">APRESIASI</span><h2>Pencapaian yang dirayakan</h2></div><a class="text-link" href="achievements.php">Semua prestasi</a></div><?php unit_cards($achievements,'achievement-grid','Prestasi akan segera ditampilkan.'); ?></div></section>
<?php unit_page_end(); return; }

$pageInfo=['profile'=>['PROFIL UNIT','Mengenal '.$settings['name'],'Komitmen pendidikan dan pengasuhan yang berpihak pada tumbuh kembang siswa.'],'programs'=>['PROGRAM','Program belajar yang bermakna','Rangkaian pembelajaran yang dirancang sesuai usia dan kebutuhan anak.'],'activities'=>['KEGIATAN','Belajar melalui pengalaman','Aktivitas yang memberi ruang bagi anak untuk aktif, berani, dan bahagia.'],'news'=>['BERITA','Kabar terbaru unit','Informasi kegiatan dan cerita terbaru dari lingkungan sekolah.'],'achievements'=>['PRESTASI','Apresiasi untuk setiap proses','Pencapaian siswa yang tumbuh dari usaha, dukungan, dan doa.'],'brochures'=>['BROSUR','Informasi pendaftaran','Unduh informasi layanan dan program '.$settings['name'].'.'],'gallery'=>['GALERI','Potret kegiatan sekolah','Kumpulan momen belajar, bermain, dan bertumbuh bersama.'],'spmb'=>['SPMB','Pendaftaran siswa baru','Isi data singkat, lalu kami arahkan ke WhatsApp unit untuk konsultasi.'],'contact'=>['KONTAK','Mari terhubung dengan kami','Tim kami siap menjawab pertanyaan Anda.']];
[$eyebrow,$title,$text]=$pageInfo[$page]??$pageInfo['profile']; unit_page_start($title,$page); unit_page_banner($eyebrow,$title,$text);
if($page==='profile'): ?>
<section class="section"><div class="shell story-grid"><img src="<?php echo unit_e(unit_media($unit_config['building_image'])); ?>" alt="Gedung <?php echo unit_e($settings['name']); ?>"><div><span class="eyebrow">TENTANG KAMI</span><h2><?php echo unit_e($settings['name']); ?></h2><p><?php echo unit_e($settings['description']); ?></p><p>Kami percaya setiap anak perlu didampingi dengan perhatian, keteladanan, dan kesempatan untuk menemukan potensinya.</p><a class="button button-primary" href="contact.php">Hubungi Kami</a></div></div></section>
<?php elseif($page==='programs'): ?><section class="section"><div class="shell"><?php unit_cards(unit_content($pdo,'program'),'program-grid','Program akan segera hadir.'); ?></div></section>
<?php elseif($page==='activities'): ?><section class="section"><div class="shell"><?php unit_cards(unit_content($pdo,'activity'),'activity-grid','Kegiatan akan segera hadir.'); ?></div></section>
<?php elseif($page==='news'): ?><section class="section"><div class="shell"><?php unit_cards(unit_content($pdo,'news'),'news-grid','Belum ada berita terbaru.'); ?></div></section>
<?php elseif($page==='achievements'): ?><section class="section"><div class="shell"><?php unit_cards(unit_content($pdo,'achievement'),'achievement-grid','Prestasi akan segera ditampilkan.'); ?></div></section>
<?php elseif($page==='brochures'): ?><section class="section"><div class="shell brochure-list"><?php foreach(unit_content($pdo,'brochure') as $item): ?><article class="brochure-row"><div><span class="eyebrow">INFORMASI UNIT</span><h2><?php echo unit_e($item['title']); ?></h2><p><?php echo unit_e($item['summary']); ?></p></div><a class="button button-primary" href="<?php echo unit_e(unit_media($item['image'])); ?>" target="_blank" rel="noopener">Unduh Brosur</a></article><?php endforeach; ?></div></section>
<?php elseif($page==='gallery'): $selected=(int)($_GET['album']??0); $albums=unit_albums($pdo); if($selected): $photos=unit_album_photos($pdo,$selected); $selectedAlbum=null;foreach($albums as $album)if((int)$album['id']===$selected)$selectedAlbum=$album; ?><section class="section"><div class="shell"><a class="text-link" href="gallery.php">Kembali ke album</a><div class="section-head"><span class="eyebrow">ALBUM</span><h2><?php echo unit_e($selectedAlbum['title']??'Galeri'); ?></h2></div><div class="photo-grid"><?php foreach($photos as $index=>$photo): ?><button class="photo-button" type="button" data-lightbox="<?php echo unit_e(unit_media($photo['image'])); ?>" data-title="<?php echo unit_e($photo['title']); ?>"><img src="<?php echo unit_e(unit_media($photo['image'])); ?>" alt="<?php echo unit_e($photo['title']); ?>"><span><?php echo unit_e($photo['title']); ?></span></button><?php endforeach; ?></div></div></section><?php else: ?><section class="section"><div class="shell album-grid"><?php foreach($albums as $album): ?><a class="album-card" href="gallery.php?album=<?php echo (int)$album['id']; ?>"><img src="<?php echo unit_e(unit_media($album['cover_image'])); ?>" alt="<?php echo unit_e($album['title']); ?>"><div><span><?php echo (int)$album['photo_count']; ?> foto</span><h2><?php echo unit_e($album['title']); ?></h2><p><?php echo unit_e($album['description']); ?></p></div></a><?php endforeach; ?></div></section><?php endif; ?>
<?php elseif($page==='spmb'): ?><section class="section"><div class="shell form-layout"><div><span class="eyebrow">PENDAFTARAN</span><h2>Mulai percakapan dengan kami.</h2><p>Lengkapi data berikut. Setelah terkirim, Anda akan diarahkan ke WhatsApp admin <?php echo unit_e($settings['name']); ?>.</p><img src="<?php echo unit_e(unit_media($unit_config['hero_image'])); ?>" alt="Kegiatan <?php echo unit_e($settings['name']); ?>"></div><form method="post" class="public-form"><input type="hidden" name="csrf" value="<?php echo unit_e(unit_csrf()); ?>"><?php if(!empty($formError)): ?><p class="form-error"><?php echo unit_e($formError); ?></p><?php endif; ?><label>Nama Orang Tua<input required name="parent_name"></label><label>Nama Calon Siswa<input required name="child_name"></label><div class="form-pair"><label>WhatsApp<input required name="phone" inputmode="tel"></label><label>Email<input type="email" name="email"></label></div><label>Pesan / Pertanyaan<textarea name="message" rows="4"></textarea></label><button class="button button-primary" type="submit">Kirim &amp; Lanjut WhatsApp</button></form></div></section>
<?php elseif($page==='contact'): ?><section class="section"><div class="shell contact-grid"><div><span class="eyebrow">KONTAK ADMINISTRASI</span><h2><?php echo unit_e($settings['name']); ?></h2><dl><dt>Alamat</dt><dd><?php echo nl2br(unit_e($settings['address'])); ?></dd><dt>Telepon</dt><dd><a href="tel:<?php echo unit_e(preg_replace('/[^0-9+]/','',$settings['phone'])); ?>"><?php echo unit_e($settings['phone']); ?></a></dd><dt>Email</dt><dd><a href="mailto:<?php echo unit_e($settings['email']); ?>"><?php echo unit_e($settings['email']); ?></a></dd></dl><div class="social-links"><a href="<?php echo unit_e($settings['instagram']); ?>" target="_blank" rel="noopener">Instagram</a><a href="<?php echo unit_e($settings['youtube']); ?>" target="_blank" rel="noopener">YouTube</a></div></div><div class="map-card"><iframe title="Peta <?php echo unit_e($settings['name']); ?>" src="https://www.google.com/maps?q=<?php echo rawurlencode($settings['address']); ?>&output=embed" loading="lazy"></iframe><a class="button button-primary" href="<?php echo unit_e($settings['maps']); ?>" target="_blank" rel="noopener">Buka Petunjuk Arah</a></div></div></section>
<?php endif; ?><div class="lightbox" data-lightbox-dialog hidden><button type="button" class="lightbox-close" data-lightbox-close aria-label="Tutup">×</button><button type="button" class="lightbox-nav prev" data-lightbox-prev aria-label="Foto sebelumnya">&#8249;</button><img src="" alt=""><button type="button" class="lightbox-nav next" data-lightbox-next aria-label="Foto berikutnya">&#8250;</button><p data-lightbox-title></p></div><?php unit_page_end();
