<?php
require_once __DIR__ . '/../../backend/config/database.php';
require_once __DIR__ . '/../../backend/helpers/functions.php';
$slug = strtolower(trim($_GET['unit'] ?? ''));
$stmt = $pdo->prepare('SELECT * FROM brochures WHERE unit_slug=? AND is_active=1 LIMIT 1'); $stmt->execute([$slug]); $brochure=$stmt->fetch();
if(!$brochure){ http_response_code(404); $page_title='Brosur Tidak Ditemukan'; require __DIR__.'/../components/header.php'; ?><section class="page-header"><div class="container"><h1>Brosur Tidak Ditemukan</h1></div></section><section class="section"><div class="container empty-public-state"><p>Unit yang dipilih tidak tersedia.</p><a class="btn btn-primary" href="brosur.php">Kembali ke Brosur</a></div></section><?php require __DIR__.'/../components/footer.php'; return; }
$page_title='Brosur '.$brochure['unit_name']; require __DIR__.'/../components/header.php';
?>
<section class="brochure-detail-hero" style="--brochure-image:url('<?php echo esc($brochure['cover_image']); ?>')"><div class="container brochure-detail-grid"><div><span class="page-kicker">Brosur <?php echo esc($brochure['unit_name']); ?></span><h1><?php echo esc($brochure['headline']); ?></h1><p><?php echo esc($brochure['description']); ?></p><div class="hero-actions brochure-actions"><?php if($brochure['file_url']): ?><a class="btn btn-gold" href="download-brosur.php?unit=<?php echo urlencode($brochure['unit_slug']); ?>">Unduh Brosur PDF</a><?php else: ?><span class="brochure-unavailable">PDF sedang disiapkan oleh sekolah.</span><?php endif; ?><a class="btn btn-outline-light" href="form-spmb.php?level=<?php echo urlencode(strtoupper($brochure['unit_slug'])); ?>">Daftar <?php echo esc($brochure['unit_name']); ?></a></div></div><div class="brochure-preview"><img src="<?php echo esc($brochure['cover_image']); ?>" alt="Program <?php echo esc($brochure['unit_name']); ?>"></div></div></section>
<section class="section"><div class="container brochure-info-grid"><div><span class="section-eyebrow">Langkah Berikutnya</span><h2>Temukan Unit yang Tepat untuk Anak</h2><p>Pelajari program, kunjungi lokasi sekolah, lalu lengkapi pendaftaran SPMB secara online. Tim sekolah akan menghubungi melalui WhatsApp.</p></div><div class="brochure-quick-links"><a href="unit.php#<?php echo esc($brochure['unit_slug']); ?>"><strong>Profil Unit</strong><span>Fasilitas dan program unggulan →</span></a><a href="kontak.php"><strong>Lokasi Sekolah</strong><span>Peta dan petunjuk arah →</span></a><a href="form-spmb.php?level=<?php echo urlencode(strtoupper($brochure['unit_slug'])); ?>"><strong>Form SPMB</strong><span>Daftar atau masuk waiting list →</span></a></div></div></section>
<?php require __DIR__.'/../components/footer.php'; ?>
