<?php
require_once __DIR__ . '/../../backend/config/database.php';
require_once __DIR__ . '/../../backend/helpers/functions.php';
$slug=strtolower(trim($_GET['unit']??'')); $stmt=$pdo->prepare('SELECT * FROM brochures WHERE unit_slug=? AND is_active=1 LIMIT 1'); $stmt->execute([$slug]); $brochure=$stmt->fetch();
if(!$brochure){ http_response_code(404); $page_title='Brosur Tidak Ditemukan'; require __DIR__.'/../components/header.php'; ?><section class="page-header"><div class="container"><h1>Brosur Tidak Ditemukan</h1></div></section><section class="section"><div class="container empty-public-state"><a class="btn btn-primary" href="brosur.php">Kembali ke Brosur</a></div></section><?php require __DIR__.'/../components/footer.php'; return; }
$brochure['cover_image']=public_media_url($brochure['cover_image']??null);
$highlights=array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)($brochure['highlights']??''))));
$facilities=array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)($brochure['facilities']??''))));
$page_title='Brosur '.$brochure['unit_name']; $meta_description=$brochure['description']; $meta_image=$brochure['cover_image']; $canonical_url=SITE_URL.'/brosur-unit.php?unit='.rawurlencode($slug); require __DIR__.'/../components/header.php';
?>
<section class="brochure-detail-hero" style="--brochure-image:url('<?php echo esc($brochure['cover_image']); ?>')"><div class="container brochure-detail-grid"><div><a class="back-link light" href="brosur.php">&larr; Semua brosur</a><span class="page-kicker">Program <?php echo esc($brochure['unit_name']); ?></span><h1><?php echo esc($brochure['headline']); ?></h1><p><?php echo esc($brochure['description']); ?></p><?php if($brochure['audience']): ?><div class="brochure-for"><small>Dirancang untuk</small><strong><?php echo esc($brochure['audience']); ?></strong></div><?php endif; ?><div class="hero-actions brochure-actions"><a class="btn btn-gold" href="download-brosur.php?unit=<?php echo urlencode($slug); ?>">Unduh Poster PDF</a><a class="btn btn-outline-light" href="form-spmb.php?level=<?php echo urlencode(strtoupper($slug)); ?>">Daftar <?php echo esc($brochure['unit_name']); ?></a></div></div><button type="button" class="brochure-poster image-preview-trigger" data-lightbox-src="<?php echo esc($brochure['cover_image']); ?>" data-lightbox-title="Poster <?php echo esc($brochure['unit_name']); ?>"><img src="<?php echo esc($brochure['cover_image']); ?>" alt="Poster <?php echo esc($brochure['unit_name']); ?>"><span>Lihat poster penuh</span></button></div></section>
<section class="section brochure-story"><div class="container"><div class="section-head"><span class="section-eyebrow">Pengalaman Belajar</span><h2>Yang akan anak dapatkan di <?php echo esc($brochure['unit_name']); ?></h2><p>Program disusun agar perkembangan akademik, adab, kemandirian, dan kecakapan sosial tumbuh secara seimbang.</p></div><div class="brochure-value-grid"><div class="brochure-value-card"><span>01</span><h3>Program Unggulan</h3><ul><?php foreach($highlights as $item): ?><li><?php echo esc($item); ?></li><?php endforeach; ?></ul></div><div class="brochure-value-card"><span>02</span><h3>Fasilitas Pendukung</h3><ul><?php foreach($facilities as $item): ?><li><?php echo esc($item); ?></li><?php endforeach; ?></ul></div><div class="brochure-value-card brochure-value-wide"><span>03</span><h3>Ritme Pendidikan</h3><p><?php echo esc($brochure['schedule_info']?:'Jadwal dan layanan disesuaikan dengan kebutuhan setiap tahap pendidikan.'); ?></p><a href="https://wa.me/<?php echo esc(SITE_WHATSAPP); ?>" target="_blank" rel="noopener">Tanyakan jadwal dan biaya terbaru &rarr;</a></div></div></div></section>
<section class="section section-alt"><div class="container brochure-info-grid"><div><span class="section-eyebrow">Langkah Berikutnya</span><h2>Siap mengenal unit lebih dekat?</h2><p>Lihat dokumentasi unit, kunjungi lokasi sekolah, atau langsung isi formulir. Tim SPMB akan melanjutkan verifikasi melalui WhatsApp.</p></div><div class="brochure-quick-links"><a href="unit.php#<?php echo esc($slug); ?>"><strong>Profil &amp; Galeri Unit</strong><span>Program, fasilitas, dan foto kegiatan &rarr;</span></a><a href="kontak.php"><strong>Lokasi Sekolah</strong><span>Peta dan petunjuk arah &rarr;</span></a><a href="form-spmb.php?level=<?php echo urlencode(strtoupper($slug)); ?>"><strong>Form SPMB</strong><span>Daftar atau masuk waiting list &rarr;</span></a></div></div></section>
<?php require __DIR__.'/../components/footer.php'; ?>
