<?php
require_once __DIR__ . '/../../backend/config/database.php';
require_once __DIR__ . '/../../backend/helpers/functions.php';
$id=(int)($_GET['id']??0); $stmt=$pdo->prepare("SELECT * FROM site_content_items WHERE id=? AND type='achievement' AND is_active=1"); $stmt->execute([$id]); $achievement=$stmt->fetch();
if(!$achievement){http_response_code(404);$page_title='Prestasi Tidak Ditemukan';require __DIR__.'/../components/header.php';?><section class="page-header"><div class="container"><h1>Prestasi Tidak Ditemukan</h1></div></section><section class="section"><div class="container empty-public-state"><a class="btn btn-primary" href="prestasi.php">Kembali ke Prestasi</a></div></section><?php require __DIR__.'/../components/footer.php';return;}
$image=$achievement['image']?:SITE_URL.'/frontend/assets/images/school/hero-school.png'; $unit=$achievement['extra']?:'Sekolah';
$page_title=$achievement['title'];$meta_description=$achievement['description'];$meta_image=$image;$meta_type='article';$canonical_url=SITE_URL.'/detail-prestasi.php?id='.$id;$shareUrl=urlencode($canonical_url);$shareText=urlencode($achievement['title']);require __DIR__.'/../components/header.php';
?>
<section class="achievement-detail-hero"><div class="container achievement-detail-grid"><div><a class="back-link light" href="prestasi.php">&larr; Semua prestasi</a><span class="page-kicker"><?php echo esc(($achievement['badge']?:'Prestasi').' · '.$unit); ?></span><h1><?php echo esc($achievement['title']); ?></h1><p><?php echo esc($achievement['description']); ?></p><div class="achievement-facts"><span><small>Unit</small><strong><?php echo esc($unit); ?></strong></span><span><small>Tingkat</small><strong><?php echo esc($achievement['badge']?:'Sekolah'); ?></strong></span><span><small>Tahun</small><strong><?php echo esc($achievement['year']?:date('Y')); ?></strong></span></div></div><button type="button" class="achievement-detail-image image-preview-trigger" data-lightbox-src="<?php echo esc($image); ?>" data-lightbox-title="<?php echo esc($achievement['title']); ?>"><img src="<?php echo esc($image); ?>" alt="<?php echo esc($achievement['title']); ?>"><span>Lihat foto penuh</span></button></div></section>
<section class="section"><div class="container achievement-story-grid"><article><span class="section-eyebrow">Cerita Prestasi</span><h2>Apresiasi untuk proses, disiplin, dan keberanian</h2><p><?php echo nl2br(esc($achievement['description'])); ?></p><p>Prestasi ini menjadi bagian dari proses panjang siswa dalam belajar, berlatih, mengelola tantangan, dan memberi hasil terbaik. Sekolah mengapresiasi dukungan guru, pembimbing, serta orang tua yang terus mendampingi.</p><div class="social-share"><span>Bagikan prestasi</span><a target="_blank" rel="noopener" href="https://wa.me/?text=<?php echo $shareText.'%20'.$shareUrl; ?>">WhatsApp</a><a target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $shareUrl; ?>">Facebook</a><a target="_blank" rel="noopener" href="https://twitter.com/intent/tweet?text=<?php echo $shareText; ?>&url=<?php echo $shareUrl; ?>">X</a><button type="button" data-native-share data-share-title="<?php echo esc($achievement['title']); ?>" data-share-url="<?php echo esc($canonical_url); ?>">Lainnya</button></div></article><aside><span class="section-eyebrow">Dukungan Sekolah</span><h3>Tumbuh melalui kesempatan nyata</h3><ul><li>Pemetaan minat dan potensi siswa</li><li>Pendampingan serta latihan terarah</li><li>Kesempatan mengikuti kegiatan dan kompetisi</li><li>Apresiasi terhadap proses dan hasil</li></ul><?php if($achievement['link_url']): ?><a class="btn btn-primary btn-block" href="<?php echo esc($achievement['link_url']); ?>" target="_blank" rel="noopener"><?php echo esc($achievement['link_label']?:'Lihat Publikasi Asli'); ?></a><?php endif; ?></aside></div></section>
<?php require __DIR__.'/../components/footer.php'; ?>
