<?php
require_once __DIR__ . '/../../backend/config/database.php';
require_once __DIR__ . '/../../backend/helpers/functions.php';
$id=(int)($_GET['id']??0); $stmt=$pdo->prepare("SELECT * FROM site_content_items WHERE id=? AND type='program' AND is_active=1"); $stmt->execute([$id]); $program=$stmt->fetch();
if(!$program){http_response_code(404);$page_title='Program Tidak Ditemukan';require __DIR__.'/../components/header.php';?><section class="page-header"><div class="container"><h1>Program Tidak Ditemukan</h1></div></section><section class="section"><div class="container empty-public-state"><a class="btn btn-primary" href="program.php">Lihat Semua Program</a></div></section><?php require __DIR__.'/../components/footer.php';return;}
$label=strtolower($program['subtitle'].' '.$program['title']);
$visual=SITE_URL.'/frontend/assets/images/gallery/kegiatan-sekolah/kegiatan-02.jpeg';
foreach(['daycare','tkit','sdit','smpit'] as $unit) if(strpos($label,$unit)!==false) $visual=SITE_URL.'/frontend/assets/images/brochures/'.$unit.'-promo.png';
if(strpos($label,'quran')!==false||strpos($label,"qur'an")!==false||strpos($label,'tahf')!==false)$visual=SITE_URL.'/frontend/assets/images/gallery/masjid-sekolah/masjid-01.jpeg';
$visual=$program['image']?:$visual;
$journey=['Pemetaan kebutuhan dan tahap perkembangan peserta didik','Pembelajaran aktif dengan target yang jelas dan terukur','Pendampingan, dokumentasi, serta evaluasi perkembangan','Kolaborasi guru dan orang tua untuk penguatan di rumah'];
$outcomes=['Anak memahami konsep melalui pengalaman nyata','Kemandirian, disiplin, dan rasa percaya diri bertumbuh','Adab serta nilai Islam hadir dalam kebiasaan sehari-hari','Perkembangan dikomunikasikan secara berkala kepada orang tua'];
$page_title=$program['title'];$meta_description=$program['description'];$meta_image=$visual;$canonical_url=SITE_URL.'/detail-program.php?id='.$id;require __DIR__.'/../components/header.php';
?>
<section class="program-detail-hero"><div class="container program-detail-grid"><div><a class="back-link light" href="program.php">&larr; Semua program</a><span class="page-kicker"><?php echo esc($program['subtitle']?:'Program Unggulan'); ?></span><h1><?php echo esc($program['title']); ?></h1><p><?php echo nl2br(esc($program['description'])); ?></p><div class="hero-actions"><a class="btn btn-gold" href="form-spmb.php">Daftar SPMB</a><a class="btn btn-outline-light" href="https://wa.me/<?php echo esc(SITE_WHATSAPP); ?>" target="_blank" rel="noopener">Konsultasi Program</a></div></div><button type="button" class="program-detail-visual image-preview-trigger" data-lightbox-src="<?php echo esc($visual); ?>" data-lightbox-title="<?php echo esc($program['title']); ?>"><img src="<?php echo esc($visual); ?>" alt="<?php echo esc($program['title']); ?>"><span>Lihat dokumentasi</span></button></div></section>
<section class="section program-experience"><div class="container"><div class="section-head"><span class="section-eyebrow">Cara Program Berjalan</span><h2>Pendampingan yang terarah, bukan sekadar kegiatan</h2><p>Setiap tahap dirancang agar tujuan program terlihat dalam pengalaman belajar dan perkembangan harian siswa.</p></div><div class="program-journey-grid"><?php foreach($journey as $index=>$item): ?><article><span>0<?php echo $index+1; ?></span><h3><?php echo esc(['Kenali Kebutuhan','Belajar Aktif','Pantau Perkembangan','Tumbuh Bersama'][$index]); ?></h3><p><?php echo esc($item); ?></p></article><?php endforeach; ?></div></div></section>
<section class="section section-alt"><div class="container program-outcome-grid"><div><span class="section-eyebrow">Dampak Program</span><h2>Perubahan yang ingin kami tumbuhkan</h2><p>Program menghubungkan pengetahuan, keterampilan, adab, dan kemampuan anak menerapkannya dalam kehidupan sehari-hari.</p><a class="btn btn-primary" href="unit.php">Lihat Unit Sekolah</a></div><div class="program-outcome-list"><?php foreach($outcomes as $index=>$item): ?><div><span><?php echo $index+1; ?></span><p><?php echo esc($item); ?></p></div><?php endforeach; ?></div></div></section>
<section class="section"><div class="container program-detail-cta"><div><span class="section-eyebrow">Informasi Lebih Lanjut</span><h2>Sesuaikan program dengan usia dan unit anak</h2><p>Tim sekolah siap membantu menjelaskan target, jadwal, dan proses pendaftaran.</p></div><div class="hero-actions"><a class="btn btn-gold" href="form-spmb.php">Mulai Pendaftaran</a><a class="btn btn-outline-light" href="program.php">Program Lainnya</a></div></div></section>
<?php require __DIR__.'/../components/footer.php'; ?>
