<?php
require_once __DIR__ . '/../../backend/config/database.php';
require_once __DIR__ . '/../../backend/helpers/functions.php';
$page_title='Unit Sekolah';
$units=fetch_school_units($pdo);
$unitSiteLinks=['daycare'=>SITE_URL.'/daycare/','tkit'=>SITE_URL.'/tkit/','sdit'=>SITE_URL.'/sdit/','smpit'=>SITE_URL.'/smpit/'];
$galleryStmt=$pdo->prepare('SELECT * FROM unit_gallery_photos WHERE unit_slug=? AND is_active=1 ORDER BY sort_order,id');
$unitGalleries=[]; foreach($units as $unit){$key=$unit['slug'];$galleryStmt->execute([$key]);$unitGalleries[$key]=$galleryStmt->fetchAll();foreach($unitGalleries[$key] as &$galleryPhoto){$galleryPhoto['image']=public_media_url($galleryPhoto['image']??null,$unit['image']);}unset($galleryPhoto);}
require_once __DIR__.'/../components/header.php';
?>
<section class="page-header"><div class="container"><span class="page-kicker">Daycare · TKIT · SDIT · SMPIT</span><h1>Unit Sekolah</h1><p>Setiap tahap memiliki pendekatan, program, dan ruang belajar yang dirancang sesuai kebutuhan tumbuh kembang siswa.</p><p class="breadcrumb"><a href="index.php">Beranda</a> / Unit Sekolah</p></div></section>
<section class="section unit-page-section"><div class="container"><?php foreach($units as $index=>$unit): ?><?php $key=$unit['slug']; $photos=array_merge([['title'=>'Gedung '.$unit['subtitle'],'description'=>'Tampilan gedung utama '.$unit['title'].'.','image'=>$unit['image']]],$unitGalleries[$key]??[]); $seen=[]; $photos=array_values(array_filter($photos,static function($photo) use (&$seen){$image=(string)($photo['image']??'');if($image===''||isset($seen[$image]))return false;$seen[$image]=true;return true;})); ?>
<article class="unit-showcase" id="<?php echo esc($key); ?>"><div class="unit-showcase-copy"><span class="unit-index">0<?php echo $index+1; ?></span><span class="section-eyebrow"><?php echo esc($unit['subtitle']?:'Unit Pendidikan'); ?></span><h2><?php echo esc($unit['title']); ?></h2><p><?php echo nl2br(esc($unit['description'])); ?></p><?php $tags=array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)$unit['extra']))); if($tags): ?><div class="unit-tags"><?php foreach($tags as $tag): ?><span><?php echo esc($tag); ?></span><?php endforeach; ?></div><?php endif; ?><div class="unit-showcase-actions"><a class="btn btn-primary" href="<?php echo esc($unitSiteLinks[$key]??('unit.php#'.$key)); ?>">Kunjungi Website Unit</a><a class="btn btn-outline" href="form-spmb.php?level=<?php echo urlencode((string)$unit['subtitle']); ?>">Daftar di Unit Ini</a><a class="btn btn-outline" href="brosur-unit.php?unit=<?php echo urlencode($key); ?>">Lihat Brosur</a></div></div>
<div class="unit-collage unit-collage-<?php echo min(count($photos),5); ?>" aria-label="Galeri <?php echo esc($unit['title']); ?>"><?php foreach($photos as $photoIndex=>$photo): ?><button type="button" class="unit-collage-item image-preview-trigger" data-lightbox-src="<?php echo esc($photo['image']); ?>" data-lightbox-title="<?php echo esc($photo['title']); ?>"><img src="<?php echo esc($photo['image']); ?>" alt="<?php echo esc($photo['title']); ?>" loading="lazy"><span><strong><?php echo esc($photo['title']); ?></strong><?php if($photo['description']): ?><small><?php echo esc($photo['description']); ?></small><?php endif; ?></span></button><?php endforeach; ?></div></article>
<?php endforeach; ?></div></section>
<?php require_once __DIR__.'/../components/footer.php'; ?>
