<?php
require_once __DIR__ . '/../../../backend/config/database.php';
require_once __DIR__ . '/../../../backend/helpers/functions.php';
require_once __DIR__ . '/../../../backend/auth.php';
portal_require_auth(['admin', 'humas']);

function career_unique_slug(PDO $pdo, string $title, int $ignoreId = 0): string {
    $base = portal_slug($title); $slug = $base; $counter = 2;
    $stmt = $pdo->prepare('SELECT COUNT(*) FROM job_vacancies WHERE slug=? AND id<>?');
    while (true) { $stmt->execute([$slug,$ignoreId]); if ((int)$stmt->fetchColumn() === 0) return $slug; $slug = $base . '-' . $counter++; }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    portal_verify_csrf();
    $action = $_POST['action'] ?? '';
    try {
        if ($action === 'save_job') {
            $id=(int)($_POST['id']??0); $title=trim($_POST['title']??''); $unit=trim($_POST['unit']??''); $department=trim($_POST['department']??'');
            $employmentType=trim($_POST['employment_type']??''); $location=trim($_POST['work_location']??''); $summary=trim($_POST['summary']??'');
            $description=trim($_POST['description']??''); $responsibilities=trim($_POST['responsibilities']??''); $requirements=trim($_POST['requirements']??'');
            if ($title===''||$unit===''||$department===''||$employmentType===''||$location===''||$summary===''||$description===''||$responsibilities===''||$requirements==='') throw new RuntimeException('Kolom utama, deskripsi, tanggung jawab, dan kualifikasi wajib diisi.');
            $slug=career_unique_slug($pdo,$title,$id);
            $previousImage=null; $image=null;
            if ($id) { $imageStmt=$pdo->prepare('SELECT image FROM job_vacancies WHERE id=?'); $imageStmt->execute([$id]); $previousImage=$imageStmt->fetchColumn()?:null; $image=$previousImage; }
            if (!empty($_FILES['image']['name'])) $image=portal_upload_image($_FILES['image'],'karir');
            $values=[$title,$slug,$unit,$department,$employmentType,$location,trim($_POST['education']??'')?:null,trim($_POST['experience']??'')?:null,$summary,$description,$responsibilities,$requirements,trim($_POST['benefits']??'')?:null,trim($_POST['salary_note']??'')?:null,$image,($_POST['deadline']??'')?:null,isset($_POST['is_featured'])?1:0,isset($_POST['is_active'])?1:0];
            if ($id) { $stmt=$pdo->prepare('UPDATE job_vacancies SET title=?,slug=?,unit=?,department=?,employment_type=?,work_location=?,education=?,experience=?,summary=?,description=?,responsibilities=?,requirements=?,benefits=?,salary_note=?,image=?,deadline=?,is_featured=?,is_active=? WHERE id=?'); $values[]=$id; $stmt->execute($values); if($previousImage&&$previousImage!==$image) portal_delete_uploaded_image($previousImage); portal_log($pdo,'update_job','Memperbarui lowongan: '.$title); }
            else { $stmt=$pdo->prepare('INSERT INTO job_vacancies (title,slug,unit,department,employment_type,work_location,education,experience,summary,description,responsibilities,requirements,benefits,salary_note,image,deadline,is_featured,is_active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'); $stmt->execute($values); portal_log($pdo,'create_job','Menerbitkan lowongan: '.$title); }
            portal_flash('success','Lowongan berhasil disimpan dan halaman Karir sudah diperbarui.');
        } elseif ($action === 'delete_job') {
            $id=(int)($_POST['id']??0); $stmt=$pdo->prepare('SELECT title,(SELECT COUNT(*) FROM job_applications WHERE vacancy_id=job_vacancies.id) applications FROM job_vacancies WHERE id=?'); $stmt->execute([$id]); $job=$stmt->fetch();
            if ($job) { if((int)$job['applications']>0){$pdo->prepare('UPDATE job_vacancies SET is_active=0 WHERE id=?')->execute([$id]); portal_flash('success','Lowongan diarsipkan karena sudah memiliki data pelamar.');}else{$pdo->prepare('DELETE FROM job_vacancies WHERE id=?')->execute([$id]); portal_flash('success','Lowongan berhasil dihapus.');} portal_log($pdo,'delete_job','Menghapus/mengarsipkan lowongan: '.$job['title']); }
        } elseif ($action === 'update_application') {
            $id=(int)($_POST['id']??0); $status=$_POST['status']??'baru'; if(!in_array($status,['baru','ditinjau','wawancara','diterima','ditolak'],true)) throw new RuntimeException('Status kandidat tidak valid.');
            $pdo->prepare('UPDATE job_applications SET status=?,admin_notes=? WHERE id=?')->execute([$status,trim($_POST['admin_notes']??'')?:null,$id]);
            portal_log($pdo,'update_application','Memperbarui status lamaran #'.$id.' menjadi '.$status); portal_flash('success','Status dan catatan kandidat berhasil diperbarui.');
        }
    } catch (Throwable $e) { portal_flash('danger',$e->getMessage()); }
    header('Location: '.SITE_URL.'/portal/careers'); exit;
}

$editJob=null; if(isset($_GET['edit'])){$stmt=$pdo->prepare('SELECT * FROM job_vacancies WHERE id=?');$stmt->execute([(int)$_GET['edit']]);$editJob=$stmt->fetch()?:null;}
$viewApplication=null; if(isset($_GET['application'])){$stmt=$pdo->prepare('SELECT a.*,v.title job_title FROM job_applications a JOIN job_vacancies v ON v.id=a.vacancy_id WHERE a.id=?');$stmt->execute([(int)$_GET['application']]);$viewApplication=$stmt->fetch()?:null;}
$showJobForm=isset($_GET['new'])||$editJob;
$jobs=$pdo->query('SELECT v.*,(SELECT COUNT(*) FROM job_applications a WHERE a.vacancy_id=v.id) application_count FROM job_vacancies v ORDER BY v.is_active DESC,v.is_featured DESC,v.created_at DESC')->fetchAll();
$applicationStatus=$_GET['status']??''; $applicationWhere='';$applicationParams=[]; if(in_array($applicationStatus,['baru','ditinjau','wawancara','diterima','ditolak'],true)){$applicationWhere=' WHERE a.status=?';$applicationParams[]=$applicationStatus;}
$stmt=$pdo->prepare('SELECT a.*,v.title job_title FROM job_applications a JOIN job_vacancies v ON v.id=a.vacancy_id'.$applicationWhere.' ORDER BY a.created_at DESC');$stmt->execute($applicationParams);$applications=$stmt->fetchAll();
$summary=$pdo->query("SELECT COUNT(*) total,SUM(status='baru') new_count,SUM(status='wawancara') interview_count,SUM(status='diterima') accepted_count FROM job_applications")->fetch();
$statusLabels=['baru'=>'Baru','ditinjau'=>'Ditinjau','wawancara'=>'Wawancara','diterima'=>'Diterima','ditolak'=>'Ditolak'];
$portalTitle='Karir & Lamaran';$portalActive='careers';require __DIR__.'/../../components/portal-header.php';
?>

<div class="portal-welcome"><div><h2>Portal Rekrutmen</h2><p>Kelola lowongan yang tampil di website dan proses seluruh lamaran kandidat.</p></div><a class="portal-action" href="<?php echo SITE_URL; ?>/portal/careers?new=1">+ Buat Lowongan</a></div>
<div class="stat-grid"><div class="stat-card"><small>Lowongan</small><strong><?php echo count($jobs); ?></strong><span>Total data</span></div><div class="stat-card"><small>Pelamar</small><strong><?php echo (int)$summary['total']; ?></strong><span>Semua posisi</span></div><div class="stat-card"><small>Lamaran baru</small><strong><?php echo (int)$summary['new_count']; ?></strong><span>Perlu ditinjau</span></div><div class="stat-card"><small>Tahap wawancara</small><strong><?php echo (int)$summary['interview_count']; ?></strong><span>Kandidat aktif</span></div></div>

<?php if($showJobForm): ?>
<section class="portal-panel" style="margin-bottom:22px"><div class="panel-head"><h3><?php echo $editJob?'Edit':'Buat'; ?> Lowongan</h3><a href="<?php echo SITE_URL; ?>/portal/careers">Tutup</a></div><form class="portal-form portal-form-grid" method="post" enctype="multipart/form-data"><input type="hidden" name="_token" value="<?php echo esc(portal_csrf_token()); ?>"><input type="hidden" name="action" value="save_job"><input type="hidden" name="id" value="<?php echo (int)($editJob['id']??0); ?>">
<div class="field"><label>Nama posisi</label><input name="title" value="<?php echo esc($editJob['title']??''); ?>" required placeholder="Guru Kelas SDIT"></div><div class="field"><label>Unit</label><input name="unit" value="<?php echo esc($editJob['unit']??''); ?>" required placeholder="SDIT / TKIT / Yayasan"></div>
<div class="field"><label>Divisi/departemen</label><input name="department" value="<?php echo esc($editJob['department']??''); ?>" required placeholder="Pendidikan"></div><div class="field"><label>Tipe pekerjaan</label><select name="employment_type" required><?php foreach(['Penuh Waktu','Paruh Waktu','Kontrak','Magang','Freelance'] as $type): ?><option <?php echo ($editJob['employment_type']??'Penuh Waktu')===$type?'selected':''; ?>><?php echo esc($type); ?></option><?php endforeach; ?></select></div>
<div class="field"><label>Lokasi kerja</label><input name="work_location" value="<?php echo esc($editJob['work_location']??'Tambun Selatan, Bekasi'); ?>" required></div><div class="field"><label>Batas lamaran</label><input type="date" name="deadline" value="<?php echo esc($editJob['deadline']??date('Y-m-d',strtotime('+60 days'))); ?>"></div>
<div class="field full"><label>Gambar lowongan / preview sosial</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp"><small style="color:var(--portal-muted)">Disarankan 1200×630 px. Dipakai pada halaman karir dan preview saat dibagikan.</small></div>
<div class="field"><label>Pendidikan</label><input name="education" value="<?php echo esc($editJob['education']??''); ?>" placeholder="S1 bidang relevan"></div><div class="field"><label>Pengalaman</label><input name="experience" value="<?php echo esc($editJob['experience']??''); ?>" placeholder="Minimal 1 tahun / Fresh graduate"></div>
<div class="field full"><label>Ringkasan singkat</label><input maxlength="255" name="summary" value="<?php echo esc($editJob['summary']??''); ?>" required></div><div class="field full"><label>Deskripsi posisi</label><textarea name="description" required><?php echo esc($editJob['description']??''); ?></textarea></div>
<div class="field"><label>Tanggung jawab (satu per baris)</label><textarea name="responsibilities" required><?php echo esc($editJob['responsibilities']??''); ?></textarea></div><div class="field"><label>Kualifikasi (satu per baris)</label><textarea name="requirements" required><?php echo esc($editJob['requirements']??''); ?></textarea></div>
<div class="field"><label>Benefit (satu per baris)</label><textarea name="benefits"><?php echo esc($editJob['benefits']??''); ?></textarea></div><div class="field"><label>Informasi kompensasi</label><input name="salary_note" value="<?php echo esc($editJob['salary_note']??'Kompetitif'); ?>" placeholder="Kompetitif / Rp ..."></div>
<div class="field full portal-check-row"><label><input type="checkbox" name="is_featured" <?php echo ($editJob['is_featured']??0)?'checked':''; ?>> Tandai sebagai posisi prioritas</label><label><input type="checkbox" name="is_active" <?php echo !isset($editJob['is_active'])||$editJob['is_active']?'checked':''; ?>> Tampilkan di website</label></div><div class="form-actions field full"><a class="portal-action secondary" href="<?php echo SITE_URL; ?>/portal/careers">Batal</a><button class="portal-action">Simpan Lowongan</button></div></form></section>
<?php endif; ?>

<?php if($viewApplication): ?>
<section class="portal-panel" style="margin-bottom:22px"><div class="panel-head"><h3>Detail Kandidat — <?php echo esc($viewApplication['full_name']); ?></h3><a href="<?php echo SITE_URL; ?>/portal/careers">Tutup</a></div><div class="candidate-detail-grid"><div><small>Posisi</small><strong><?php echo esc($viewApplication['job_title']); ?></strong></div><div><small>Email</small><strong><?php echo esc($viewApplication['email']); ?></strong></div><div><small>WhatsApp</small><strong><?php echo esc($viewApplication['phone']); ?></strong></div><div><small>Domisili</small><strong><?php echo esc($viewApplication['city']?:'-'); ?></strong></div><div><small>Pendidikan</small><strong><?php echo esc($viewApplication['education']?:'-'); ?></strong></div><div><small>Pengalaman</small><strong><?php echo esc($viewApplication['experience_years']); ?> tahun</strong></div></div><div class="candidate-letter"><small>Pengantar lamaran</small><p><?php echo nl2br(esc($viewApplication['cover_letter'])); ?></p></div><div class="candidate-links"><a class="portal-action secondary" target="_blank" rel="noopener" href="<?php echo esc($viewApplication['cv_file']); ?>">Buka CV</a><?php if($viewApplication['portfolio_url']): ?><a class="portal-action secondary" target="_blank" rel="noopener" href="<?php echo esc($viewApplication['portfolio_url']); ?>">Buka Portofolio</a><?php endif; ?></div><form class="portal-form portal-form-grid" method="post" style="margin-top:20px"><input type="hidden" name="_token" value="<?php echo esc(portal_csrf_token()); ?>"><input type="hidden" name="action" value="update_application"><input type="hidden" name="id" value="<?php echo (int)$viewApplication['id']; ?>"><div class="field"><label>Status kandidat</label><select name="status"><?php foreach($statusLabels as $key=>$label): ?><option value="<?php echo $key; ?>" <?php echo $viewApplication['status']===$key?'selected':''; ?>><?php echo $label; ?></option><?php endforeach; ?></select></div><div class="field full"><label>Catatan internal</label><textarea name="admin_notes"><?php echo esc($viewApplication['admin_notes']); ?></textarea></div><div class="form-actions field full"><button class="portal-action">Simpan Status Kandidat</button></div></form></section>
<?php endif; ?>

<section class="portal-panel" style="margin-bottom:22px"><div class="panel-head"><h3>Daftar Lowongan (<?php echo count($jobs); ?>)</h3></div><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Posisi</th><th>Unit & Tipe</th><th>Deadline</th><th>Pelamar</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($jobs as $job): ?><tr><td><strong><?php echo esc($job['title']); ?></strong><br><small><?php echo esc($job['department']); ?></small></td><td><?php echo esc($job['unit']); ?><br><small><?php echo esc($job['employment_type']); ?></small></td><td><?php echo $job['deadline']?esc(tanggal_indo($job['deadline'])):'Terbuka'; ?></td><td><?php echo (int)$job['application_count']; ?></td><td><span class="status <?php echo $job['is_active']?'active':'inactive'; ?>"><?php echo $job['is_active']?'Tayang':'Arsip'; ?></span></td><td><div class="table-actions"><a class="portal-action secondary small" href="<?php echo SITE_URL; ?>/portal/careers?edit=<?php echo (int)$job['id']; ?>">Edit</a><a class="portal-action secondary small" target="_blank" href="<?php echo SITE_URL; ?>/detail-karir.php?slug=<?php echo urlencode($job['slug']); ?>">Lihat</a><form method="post" onsubmit="return confirm('Hapus atau arsipkan lowongan ini?')"><input type="hidden" name="_token" value="<?php echo esc(portal_csrf_token()); ?>"><input type="hidden" name="action" value="delete_job"><input type="hidden" name="id" value="<?php echo (int)$job['id']; ?>"><button class="portal-action danger small">Hapus</button></form></div></td></tr><?php endforeach; ?></tbody></table></div></section>

<section class="portal-panel"><div class="panel-head"><h3>Lamaran Masuk (<?php echo count($applications); ?>)</h3></div><form class="filters" method="get"><select name="status"><option value="">Semua status</option><?php foreach($statusLabels as $key=>$label): ?><option value="<?php echo $key; ?>" <?php echo $applicationStatus===$key?'selected':''; ?>><?php echo $label; ?></option><?php endforeach; ?></select><button class="portal-action small">Filter</button><a class="portal-action secondary small" href="<?php echo SITE_URL; ?>/portal/careers">Reset</a></form><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Kandidat</th><th>Posisi</th><th>Kontak</th><th>Masuk</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(!$applications): ?><tr><td colspan="6" class="empty-state">Belum ada lamaran.</td></tr><?php endif; ?><?php foreach($applications as $application): ?><tr><td><strong><?php echo esc($application['full_name']); ?></strong><br><small><?php echo esc($application['education']?:'Pendidikan belum diisi'); ?></small></td><td><?php echo esc($application['job_title']); ?></td><td><?php echo esc($application['email']); ?><br><small><?php echo esc($application['phone']); ?></small></td><td><?php echo esc(tanggal_indo($application['created_at'])); ?></td><td><span class="status career-<?php echo esc($application['status']); ?>"><?php echo esc($statusLabels[$application['status']]??$application['status']); ?></span></td><td><a class="portal-action secondary small" href="<?php echo SITE_URL; ?>/portal/careers?application=<?php echo (int)$application['id']; ?>">Proses</a></td></tr><?php endforeach; ?></tbody></table></div></section>

<?php require __DIR__.'/../../components/portal-footer.php'; ?>
